@startuml

start

note left
    Храним в модели
    ----
    - Все границы
    - coef_
    - Трейдер:
    -- Упорядоченный список
       незадействованных долей формата:
       [нижняя доля, ..., верхняя доля]
    -- Таблицу задействованных долей с полями:
       (доля, смещение границы, кол-во покупок,
       общая сумма покупки,
       отсчет вертикальной границы продажи)
    -- Дата последней покупки
    -- Дата последней продажи
    -- Граница последней продажи
end note

note right
    От Егора
    ----
    - доли диверсификации
    - ограничение на торговлю
    - текущая дата
end note

if (текущая дата == дата последней покупки или продажи) then (да)
    :Возвращаем ноль;
    end
endif

partition Продажа {
    if (текущая реальная цена <= нижней критической границы) then (да)
        partition _sell_all {
            :Продаем все для всех долей;
            :Исключаем все границы покупок
            для всех долей из трейдера;
            :Запоминаем последнюю дату продажи
            и границу продажи;
        }
        :Возвращаем положительное число:
        сумма продажи за вычетом комиссии;
        end
    endif

    if (self.coef_ < 0) then (да)
        partition "Жадная продажа" {
            repeat
            if (
            Текущая реальная цена >=
            следующей границе после
            последней покупки очередной доли
            ) then (да)
                partition _sell_items_recent_buy {
                    :Продаем столько предметов
                    сколько указано для данной границы;
                    :Исключаем границу для этой доли
                    из памяти трейдера;
                    :Запоминаем последнюю дату продажи
                    и границу продажи;
                }
            endif
            repeat while (есть ли еще доли удовлетворяющие условию?) is (да) not (нет)

            if (Происходит убывание среднего?) then (да)
                repeat
                if (Номер текущего отсчета >= последнему прибыльному отсчету последней покупки) then (да)
                    partition _sell_items_recent_buy {
                        :Продаем столько предметов
                        сколько указано для данной границы;
                        :Исключаем границу для этой доли
                        из памяти трейдера;
                        :Запоминаем последнюю дату продажи
                        и границу продажи;
                    }
                endif
                repeat while (есть ли еще доли удовлетворяющие условию?) is (да) not (нет)
            endif
        }
    else (нет)
        :В обороте не может быть более одной доли (не ограничение);
        partition "Ленивая продажа" {
            if (
            Из данного набора границ
            (все которые выше границы покупки) есть ли те которые:
            текущая реальная цена <= граница < прошлое усреднение
            ) then (да)
                partition _sell_all {
                    :Продаем все;
                    :Исключаем единственную границу покупки из трейдера;
                    :Запоминаем последнюю дату продажи
                    и границу продажи;
                }
            endif
        }
    endif

    if (Сумма продажи отлична от нуля?) then (да)
        :Возвращаем положительное число:
        сумма продажи за вычетом комиссии;
        end
    endif
}

partition Покупка {
if (self.coef_ < 0) then (да)
partition "Ленивая покупка"{
:Задаем решающее значение средним значением за текущий шаг;
:Покупка по заданному решающему значению}
}
else
partition "Жадная покупка"{
:Задаем решающее значение текущем реальным значением;
:Покупка по заданному решающему значению}
}
endif

if (Сумма покупки отлична от нуля?) then (да)
:Возвращаем отрицательное число: сумма продажи;
end
else (нет)
:Возвращаем ноль;
end
endif
}

partition "Покупка по заданному решающему значению" #CCCCEE {
start
:Получаем количество свободных долей (КСД);
if (КСД == 0) then (да)
:Возвращаем ноль;
end
endif
:Назначаем доступными границами (ДГ) границы в срезе [1, -2];
if (
КСД != общему количеству долей
(есть текущие сделки?).
) then (да)
:Переназначаем ДГ на все границы меньше
наименьшей границы покупки текущих сделок
из границ в срезе [1, -2].
Так как последняя покупка имеет самую
низкую границу, берем все границы
в срезе [1, -2], которые меньше
границы последней покупки.;
endif
if (ДГ отсутствуют?) then (да)
:Возвращаем ноль;
end
endif
if (
not (решающее значение >= ДГ > прошлое усреднение).
Цена не растет?
) then (да)
:Возвращаем ноль;
end
endif
if (КСД == 1) then (да)
:Назначаем суммой покупки равной
оставшемуся количеству средств;
else (нет)
:Назначаем суммой покупки равной
сумму соответствующей очередной доле;
endif
:Покупаем на заданную сумму;
:Сохраняем в Трейдера данные о
доле покупки и дате покупки;
stop
}

@enduml
