@startuml

start

note left
    Храним в модели
    ----
    - Все границы
    - coef_
    - Трейдер:
    -- Упорядоченный список
       незадействованных долей формата:
       [нижняя доля, ..., верхняя доля]
    -- Таблицу задействованных долей с полями:
       (доля, смещение границы, кол-во покупок,
       общая сумма покупки,
       отсчет вертикальной границы продажи)
    -- Дата последней покупки
    -- Дата последней продажи
    -- Граница последней продажи
end note

note right
    От Егора
    ----
    - доли диверсификации
    - ограничение на торговлю
    - текущая дата
end note

if (текущая дата == дата последней покупки или продажи) then (да)
    :Возвращаем ноль;
    end
endif

partition Продажа {
    if (текущая реальная цена <= нижней критической границы) then (да)
        partition _sell_all {
            :Продаем все для всех долей;
            :Исключаем все границы для всех долей из трейдера;
            :Запоминаем последнюю дату продажи
            и границу продажи;
        }
        :Возвращаем положительное число:
        сумма продажи за вычетом комиссии;
        end
    endif

    if (self.coef_ < 0) then (да)
        partition "Жадная продажа" {
            if (
            Из данного набора границ
            (верхние границы следующие сразу за границей
            покупки) есть ли те которые:
            текущая реальная цена >= граница > прошлое усреднение
            ) then (да)
                partition _sell_items_for_bound {
                    :Продаем столько предметов
                    сколько указано для данной границы;
                    :Исключаем границу для этой доли
                    из памяти трейдера;
                    :Запоминаем последнюю дату продажи
                    и границу продажи;
                }
            endif

            if (
            Значение номера отсчета (или последующих
            отсчетов) пересечения (округление в меньшую
            сторону) следующей верхней границы от покупки
            и горизонтальной прямой (с учетом комиссии
            покупки и продажи) >= значению регрессии
            на текущем отсчете?
            ) then (да)
                partition _sell_items_for_bound {
                    :Продаем столько предметов
                    сколько указано для данной границы;
                    :Исключаем границу для этой доли
                    из памяти трейдера;
                    :Запоминаем последнюю дату продажи
                    и границу продажи;
                }
            endif
        }
    else (нет)
        partition "Ленивая продажа" {
            if (
            Из данного набора границ
            (все которые выше границы покупки) есть ли те которые:
            текущая реальная цена <= граница < прошлое усреднение
            ) then (да)
                partition _sell_all {
                    :Продаем все для всех долей;
                    :Исключаем все границы для всех долей из трейдера;
                    :Запоминаем последнюю дату продажи
                    и границу продажи;
                }
            endif
        }
    endif

    if (Сумма продажи отлична от нуля?) then (да)
        :Возвращаем положительное число:
        сумма продажи за вычетом комиссии;
        end
    endif
}

partition Покупка {
    if (self.coef_ < 0) then (да)
        partition "Ленивая покупка"{
            if (
            Из заданного набора границ
            ([1, -2] < границы прошлых покупок) минус
            граница последней покупки
            если минимум меньше трети нижнего коридора этой границы
            есть те которые:
            текущая средняя цена на шаге >= граница > прошлое усреднение
            ) then (да)
                partition _buy_with_part_of_funds {
                    if (Доля последняя?) then (да)
                        :Покупаем на все оставшиеся средства;
                    else (нет)
                        :Покупаем на все средства очередной доли;
                    endif
                    :Сохраняем в трейдера границу покупки;
                }
            endif
        }
    else
        partition "Жадная покупка"{
            if (
            Из заданного набора границ
            ([1, -2] < границы прошлых покупок) минус
            граница последней покупки
            если минимум меньше трети нижнего коридора этой границы
            есть те которые:
            текущая реальная цена >= граница > прошлое усреднение
            ) then (да)
                partition _buy_with_part_of_funds {
                    if (Доля последняя?) then (да)
                        :Покупаем на все оставшиеся средства;
                    else (нет)
                        :Покупаем на все средства очередной доли;
                    endif
                    :Сохраняем в трейдера границу покупки;
                }
            endif
        }
    endif

    if (Сумма покупки отлична от нуля?) then (да)
        :Возвращаем отрицательное число: сумма продажи;
        end
    else (нет)
        :Возвращаем ноль;
        end
    endif
}

@enduml
